### ISSUE TITLE
AutoSize Container has 0-width in corner case

### ISSUE THREAD

**Issue by default0** [ppy/osu-framework#1167]
```C#
new Container
{
    Anchor = Anchor.TopLeft,
    Origin = Anchor.TopRight,
    Position = new Vector2(200f, 200f),
    AutoSizeAxes = Axes.Both,
    Child = new SpriteText
    {
        Anchor = Anchor.TopLeft,
        Origin = Anchor.TopRight,
        AutoSizeAxes = Axes.Both,
        TextSize = 16f,
        Text = "My parent has a width of 0 :-("
    }
}
```

The above container will despite being AutoSize and despite its only child having a size (and not being RelativeSized) have a width of 0. I'm unsure as to whether that is intended behaviour or a bug, but it doesn't seem right to me.
Clarification for why this occurs or a fix if it happens to be a bug would be greatly appreciated.
Alternatively, a good workaround for wrapping a right-to-left SpriteText in a container that actually works would be pretty handy too.

**Comment by Tom94** [comment]
This is indeed intentional. The behaviour of `AutoSizeAxes` is to automatically resize a container to the smallest size that fits all children. In your case, the child has `Anchor = TopLeft` and `Origin = TopRight`, which means that the child is _always_ fully outside of its parent, regardless of its parent's size. Thus, the child is ignored for AutoSize computation.

**Comment by default0** [comment]
Since this is intended behaviour, it is notable that applying BlurEffect (or anything building on BlurEffect, such as OutlineEffect) is broken for SpriteTexts like the above, since they create this exact situation.
