### ISSUE TITLE
Implement video decoding

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#1348]
Should be exposed as a `Sprite` with a rolling texture. Using FFMPEG or similar - should be able to decode h264/mpeg-4 at least.

**Comment by FreezyLemon** [comment]
Instead of using FFmpeg as a whole, maybe use the included library "libavcodec" directly ([short explanation](https://www.ffmpeg.org/libavcodec.html), [docs](https://www.ffmpeg.org/doxygen/trunk/group__libavc.html)) since we only want video decoding, right?
This would require
1. Figuring out if the licence allows this (I think so, but the FFmpeg licensing is very complicated and I'm not sure) **and** what kind of "this program uses FFmpeg" shenanigans would be needed 
2. Writing wrappers and doing the decoding somewhat manually (see docs above)

Not sure if this would be an unnecessary case of "reinventing the wheel", but we don't need the "complete FFmpeg package", so this might be a discussion worth having..

**Comment by peppy** [comment]
That's what stable already does, FWIW.

**Comment by FreezyLemon** [comment]
I guess that code could be reused, unless you want it to be rewritten from scratch. It'd probably just have to be adjusted to work with a newer version of the codec (I'd guess the stable version is out of date) and then be implemented into the drawables. Right?

**Comment by peppy** [comment]
I'm not sure if this is still required, but to get memory stream based file loading into avcode (as opposed to from a disk path) I [added it manually](https://github.com/ppy/FFmpeg/tree/memory-protocol). We'd need to see if this can already be done in newer releases.

**Comment by ILOVEPIE** [comment]
Want me to get started working on this?

**Comment by ILOVEPIE** [comment]
I'll get started on this tomorrow, I've got a few ideas on how to implement stream based file loading.

**Comment by LovelyA72** [comment]
in opsu!, the game will extract a huuuge ffmpeg executable to ''native'' folder. And depends on the OS it running, it will extract different ffmpeg for different OS. And that can also make lazer easier to run on different OS.

**Comment by peppy** [comment]
Added a bounty for this one, as it would be useful for us to have short-term for tournament streaming improvements.
