### ISSUE TITLE
GLWrapper infinitely queues operations in headless operation

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#1473]
This is a potential memory leak over long headless operation.

`expensive_operations_queue` and `reset_scheduler` currently receive operations to queue even in headless operation, where they are never dequeued.

**Comment by FreezyLemon** [comment]
Would just clearing these occasionally be too hacky?
I'd say that preventing these operations from being scheduled at all is a lot more involved than just clearing the buffers occasionally, and basically accomplishes the same thing here.

**Comment by FreezyLemon** [comment]
So.. the only place where actions are added to `reset_scheduler` would be [here](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/OpenGL/GLWrapper.cs#L71).

This does not actually queue anything in a headless state though since the `HeadlessGameHost` doesn't call `GLWrapper.Initialize` (-> `host` is null).

So the only actual possibility of a memory leak would be `expensive_operations_queue`..
Still investigating on that one.
