### ISSUE TITLE
Improve touchscreen support on desktop platforms

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#1514]
Currently clicks are being handled incorrectly, and generally support doesn't exist.

Check out https://blogs.msdn.microsoft.com/dotnet/2017/04/05/announcing-the-net-framework-4-7/ (search `WPF Touch/Stylus support for Windows 10`) for a potential good starting point for better windows touch handling.

**Comment by FreezyLemon** [comment]
This looks really nice, but is probably not usable in osu-Framework since all the required classes are in `PresentationCore.dll` which is the WPF "core" module ([example 1](https://docs.microsoft.com/en-us/dotnet/api/system.windows.input.stylus?view=netframework-4.7.1), [2](https://docs.microsoft.com/en-us/dotnet/api/system.windows.input.touch?view=netframework-4.7.1)).
I'm not sure whether adding this as a dependency is wanted.. though just as a reference, I'll mention that the file is ~1.3MB in size.

We might be able to implement this at a lower level in Windows (look at example 2, especially the `FrameReported` event, there are strong hints at it just being a native win API function call) without needing those classes though.

**Comment by SpyHoodle** [comment]
Peppy, so your saying you don't know how to fix a massive hole in the upcoming osu!?
I'm playing with tablet on lazer and it doesnt work at all.
Please find SOME way to fix

**Comment by peppy** [comment]
That was never said, no. It is just pending behind hundreds of other tasks that also need to be completed. Please have some patience.

**Comment by SpyHoodle** [comment]
;-; soz

**Comment by VPeruS** [comment]
WPF will be available in 3.0 but only for windows

**Comment by iiSaLMaN** [comment]
Seems to be a high priority for touchscreen users.
