### ISSUE TITLE
unable to load bass.dll on linux

### ISSUE THREAD

**Issue by LastExceed** [ppy/osu-framework#1540]
ppy/osu#2386 is framework related. I (and a friend of mine too) just tested it myself on `Ubuntu 18.04 LTS` with the latest `master` (by trying to start the visual tests) to confirm that the problem is still present and not related to a specific setup but linux in general.

**Comment by SlowLogicBoy** [comment]
I did some digging on this one, since I have the same problem.
I tried looking where linux searches for those libraries by adding 
`"LD_DEBUG" : "libs cat"` 
environment variable, and it seems that it doesn't look for those libraries in output directory.
I added additional search path via environment variable: 
`"LD_LIBRARY_PATH" : "/home/{user}/code/osu/osu.Desktop/bin/Debug/netcoreapp2.0/x64"` 
and it loaded those libraries fine (I had to rename libbass.x64.so to libbass.so and move to `x64` directory). However it seems that specifying `LD_LIBRARY_PATH` env variable is considered harmful.
I added those in launch.json under `"name": "osu! (Debug, netcoreapp2.0)",` section:
```json
"env": {
     "LD_DEBUG" : "libs cat",
     "LD_LIBRARY_PATH" : "/home/{user}/code/osu/osu.Desktop/bin/Debug/netcoreapp2.0/x64"
},
```
I guess this could work as a temporary workaround, for those who really need it.
Some Info:
.net core sdk 2.1 preview 2
Linux Mint 18.3 (Ubuntu 16.04 LTS)
