### ISSUE TITLE
Ability to group test cases

### ISSUE THREAD

**Issue by jorolf** [ppy/osu-framework#1957]
Right now test cases are ordered alphabetically which leads to them being "all over the place" and hard to find, especially in osu.Game.Tests.
![osu.Game.Tests](https://user-images.githubusercontent.com/12570757/46921716-21792e00-cfff-11e8-95a4-78e5e115b9c2.png)

Possible design:
![design](https://user-images.githubusercontent.com/12570757/46921699-fabaf780-cffe-11e8-9f8d-1c7b0aa3a6b2.png)

**Comment by smoogipoo** [comment]
@arflyte Could you design something for this? (osu-framework)

**Comment by arflyte** [comment]
![illustrator_181015-151217](https://user-images.githubusercontent.com/3632750/46932900-c261fa80-d08c-11e8-8a34-8af4562808e4.png)

Added to the new design.

**Comment by jorolf** [comment]
@arflyte the design you posted doesn't line up with the current design (see screenshot). Should the new design be implemented or should I try to get it working with the current design?

**Comment by peppy** [comment]
If you are willing to implement the full new design, I don't think anyone will complain. I am willing to bounty that as well, since it's something we would love to see happen.

**Comment by jorolf** [comment]
How does the full new design look?

**Comment by andy840119** [comment]
![image](https://user-images.githubusercontent.com/9100368/52176941-2d2e7180-27f5-11e9-978f-96315d58be8f.png)
does red one means `Group name`
and the blue one means `TestCase name` ?

**Comment by peppy** [comment]
Correct. Ignore the text (which makes it a bit confusing).

**Comment by jorolf** [comment]
1. The ones without an arrow are top level test cases, right?
2. Should I adjust the basic designs or should I create new classes just for this?

This is what I have currently:
![testcases](https://user-images.githubusercontent.com/12570757/52177120-c7be8e80-27bc-11e9-9935-048c36ee1620.png)

**Comment by peppy** [comment]
The ones with arrows are groups, which would be a new concept that we don't have currently (probably using an attribute?)

Adjusting existing designs is fine. We have basically decided that the framework `Basic` classes should use this new design language and we should make them flexible for osu (and other project) usage on a per class basis. Usually it's expected that the end user will create their own implementation if they want more flexibility than the `Basic` classes offer, rather than extending those.
