### ISSUE TITLE
Invalidation does not always propagate to children when it needs to.

### ISSUE THREAD

**Issue by Tom94** [ppy/osu-framework#223]
This is best explained by an example scenario.

`Drawable drawable;`
`Container container = new Container { Children = new[] { drawable = new Drawable(); } };`
`container.Invalidate(Invalidation.All);`
`DoStuff(drawable.ScreenSpaceDrawQuad);`
`container.Invalidate(Invalidation.Colour);`

Now future invalidations of `container` will never propagate to `drawable` because everything within `container` is already invalidated, even though `drawable.ScreenSpaceDrawQuad` is still valid.

I fixed this particular scenario in https://github.com/ppy/osu-framework/pull/220/commits/fd135a3b01e69c134838d93f891eab039fef5ca6 by making `Invalidation.Color` invalidate both `DrawInfo` and `ScreenSpaceDrawQuad` but the fix is specific and does not address this class of problem in general.

- Fixes https://github.com/ppy/osu/issues/7273.

**Comment by peppy** [comment]
@Tom94 is this still an issue?

**Comment by Tom94** [comment]
Yup, it still is. Note, that currently this is not a correctness problem, but rather makes invalidations slightly more inefficient than they could be. More specifically: if something like `Color` is invalidated, then the entire `DrawInfo` gets invalidated; potentially for the subtree if it depends on the `DrawInfo` of its parent.

**Comment by peppy** [comment]
Just for documentation, there are a few special cases coded in to handle the fallout effects of this:

https://github.com/ppy/osu-framework/pull/1416/commits/baba2699d52b5ff5919f7dea29b2a7a186d6a75d#diff-74fa55675af99d2ab8d5ed0f726caf41R332

and

https://github.com/ppy/osu-framework/blob/fa6b8c6a172cc4b3645fb9b07f2227e8135fdbe4/osu.Framework/Graphics/Containers/FlowContainer.cs#L90

**Comment by ekrctb** [comment]
An another case is illustrated in #1803 `FillFlow2` and `FillFlow2Simplified`.

**Comment by ekrctb** [comment]
I think this invariant should be maintained:
- If a `Cached` (Say `A`) is invalid then other `Cached` (Say `B`) which depends on `A` should be invalid.
```csharp
Parent:
  Cached<TypeA> Abacking;
  TypeA A => Abacking.IsValid ? Abacking.Value : (Abacking.Value = ComputeA());
  TypeA ComputeA() => ...;
Child:
  Cached<TypeB> Bbacking;
  TypeB B => Bbacking.IsValid ? Bbacking.Value : (Bbacking.Value = ComputeB());
  TypeB ComputeB() => someFunc(Parent.A).
  invariant: !Bbacking.IsValid || Parent.Abacking.IsValid;
```

**Comment by smoogipoo** [comment]
Suppose there are two invalidations, `I1` and `I2`.
Suppose there are two drawables, `X` and `Y` with `X` containing `Y`.

Suppose `X` has one cached value, `C1`, and `Y` has one cached value, `C2`.

Suppose `X` responds to both `I1` and `I2` and invalidates `C1`.
Suppose `Y` responds to `I2` and invalidates `C2`.

1. `X` invalidates with `I1`, it invalidates `C1`, propagates to `Y`, which then proceeds to do nothing.
2. `X` invalidates with `I2`, it sees that `C1` is already invalid, so it doesn't propagate. `Y` cannot respond to `I2` because `X` has determined it unnecessary to be propagated.

It seems like you're suggesting that `C2` should depend on `C1`, but I have not mentioned anything about the relationship between `C1` and `C2` - for all we know they may be completely independent of each other.

Rather the issue is that `I1` and `I2` both touch _the same_ cached value.

**Comment by ekrctb** [comment]
That case can be implemented as follows:
1. There are cached properies `CI1` and `CI2`.
2. `X.C1` depends on both `X.CI1` and `X.CI2`.
3. `Y.C2` depends on `X.CI2`.

**Comment by smoogipoo** [comment]
Here's another case of this happening:

```
public class TestCaseScratch : TestCase
{
    public TestCaseScratch()
    {
        Child = new TestContainer
        {
            RelativeSizeAxes = Axes.Both,
            Size = new Vector2(0.5f),
            Child = new FillFlowContainer
            {
                RelativeSizeAxes = Axes.Both,
                Direction = FillDirection.Horizontal,
                Children = new Drawable[]
                {
                    new Box
                    {
                        RelativeSizeAxes = Axes.Both,
                        Width = 0.5f,
                        Colour = Color4.Red
                    },
                    new Box
                    {
                        RelativeSizeAxes = Axes.Both,
                        Width = 0.5f,
                        Colour = Color4.Green
                    },
                }
            },
        };
    }

    private class TestContainer : CompositeDrawable
    {
        public Drawable Child
        {
            set => childContainer.Child = value;
        }

        private readonly Container childContainer;

        public TestContainer()
        {
            InternalChild = childContainer = new Container();
        }

        protected override void Update()
        {
            base.Update();

            childContainer.Size = DrawSize;
        }
    }
}
```

`B.Invalidate(DrawSize)` doesn't get propagated on resize.

**Comment by smoogipoo** [comment]
```csharp
public class TestSceneFillFlowContainer : TestScene
{
    public TestSceneFillFlowContainer()
    {
        TestContainer testContainer;
        Add(testContainer = new TestContainer
        {
            RelativeSizeAxes = Axes.Both,
            Child = new FillFlowContainer
            {
                RelativeSizeAxes = Axes.Both,
                Height = 0.25f,
                Children = new[]
                {
                    new Box
                    {
                        RelativeSizeAxes = Axes.Both,
                        Colour = Color4.Beige,
                        Width = 0.2f,
                    },
                    new Box
                    {
                        RelativeSizeAxes = Axes.Both,
                        Colour = Color4.Bisque,
                        Width = 0.2f,
                    },
                    new Box
                    {
                        RelativeSizeAxes = Axes.Both,
                        Colour = Color4.Aquamarine,
                        Width = 0.2f,
                    },
                    new Box
                    {
                        RelativeSizeAxes = Axes.Both,
                        Colour = Color4.Cornsilk,
                        Width = 0.2f,
                    },
                }
            }
        });

        AddSliderStep("Adjust scale", 0.5, 1.5, 1.0, b => testContainer.AdjustScale((float)b));
        AddStep("Invalidate layout", () => testContainer.Invalidate());
    }

    private class TestContainer : Container<Drawable>
    {
        public void AdjustScale(float scale = 1.0f)
        {
            this.ScaleTo(new Vector2(scale));
            this.ResizeTo(new Vector2(1 / scale));
        }
    }
}
```

**Comment by smoogipoo** [comment]
Going to bump this up from candidate since we're reaching more and more cases where this is an issue.

**Comment by smoogipoo** [comment]
As a bit of an update, I've started working on this issue in https://github.com/smoogipoo/osu-framework/tree/invalidation-rework .

I've come up with the following structure:

```
Drawable A:
    - Layout L_A
    - Drawable B:
       - Layout L_B
       - Drawable C
    - Drawable B_1
```

### `Invalidate(A, type)`

1. If `{ A, L_A, B, B_1 }` have already been invalidated with all of the given invalidation type flags, stop execution, otherwise:
2. Invalidate the layout of `A`.
2. Recursively invalidate the layout dependencies `{ L_A, B, B_1 }`.

### `Validate(L_B, type)`

1. If ` { L_B }` has already been validated with all of the given invalidation type flags, stop execution.
2. Validate `{ L_B }`.
3. Recursively validate the dependent layout `{ B }`.

### Explanation

For a given subtree, we only care about two states:
1. The entire subtree is invalidated.
2. Any of the subtree is validated.

During the validation stage, we make sure that (2) is satisfied. Since we only care about _any_ being validated we can avoid the O(N^2) complexity by validating the dependents only once for any particular invalidation type.

During the invalidation stage, since the previous validation has propagated upwards, we know when a particular hierarchy will need a validation at some point. This will fix this issue, and will also allow us to optimise our invalidations a bit more (see the original commit mentioned in the OP).

There is one edge case that I've yet to tackle in my WIP branch, which is when a layout is conditionally invalidated (e.g. `SpriteText` or `DrawColourInfo` for size changes).
