### ISSUE TITLE
Standardise and enforce class ordering

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#2278]
At some point we want to automate/ci this, but for the time being this is just documentation of an ordering that we can agree on. Open for comment.

```
class
{
    public field;
	public property { get; set; } (simple)
    protected field;
	protected property { get; set; } (simple)
    private field;

    ctor()
    private load()

    public method();
	public property { get; set { // stuff } } (multiline impl.)
    protected method();
    private method();

    #region
    public method();
    protected method();
    private method();
    #endregion

    public Dispose();
}
```

**Comment by HoLLy-HaCKeR** [comment]
Is the use of many regions encouraged or should it only be used when grouping a large amount of methods?

**Comment by peppy** [comment]
Regions (for me at least) are a last resort when further extracting classes is not possible. They are good in helping group logic in classes which are over 500 lines or so.

**Comment by UselessToucan** [comment]
What about [Dispose pattern implementation](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose)? Where it's members should be placed? (public method, protected method, finalizer, private field)

**Comment by peppy** [comment]
Where dispose is shown in the opening post

**Comment by smoogipoo** [comment]
I highly prefer complex public properties to appear to appear above public methods since more often than not they represent data but have a complex `set` implementation, [SpriteText](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/Sprites/SpriteText.cs) for example (although it doesn't have many public methods).
I'd say the same for protected/private properties too, alongside their respective accessors.

The position of `CreateChildDependencies()` needs to be considered if it's enforceable by R#. I believe it should be below `load()`, because it is technically part of the "ctor region".

Again, if enforceable, I firmly believe abstract methods and simple virtual methods should be at the bottom of the class, ordered virtual then abstract and public then protected. This makes it easy to read a class and know what access you have when deriving it. [ModelBackedDrawable](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/Containers/ModelBackedDrawable.cs) is an example, [SpriteText](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/Sprites/SpriteText.cs) to a lesser degree.  
As I've shown, different editors don't sort by derivation order in their intellisense listing.  
From the standpoint of reviewing code, I want to know exactly what API is provided to the user.

The rest I agree with.

**Comment by arphox** [comment]
Referencing ppy/osu/#4927 for visibility.

**Comment by arphox** [comment]
Based on the template, I think we will need a custom Roslyn analyzer for that, since the built in rules usually are not customizable to the extent of method names.

**Comment by Joehuu** [comment]
I investigated a way to automate this. There seems to be a configuration already:
https://github.com/ppy/osu-framework/blob/9a50bc4b11def8aecff3f6eb0aa49cfd5c1278dd/osu-framework.sln.DotSettings#L370-L753

It's not configured right (expected as it's been there since the project is created), so it has to be fixed with the current config or redone using empty/default configs.

Rider can utilize this config. Not sure if it had this feature before, but for individual files, you can go to `Code` -> `Rearrange Code` and it'll apply the ordering.

For all files, you can go to `Code` -> `Reformat and Cleanup...`. There also seems to be a peppy cleanup config and rearrange code intentionally off(?):
<img width="435" alt="Screenshot 2023-01-28 at 6 03 16 PM" src="https://user-images.githubusercontent.com/35318437/215300302-d40fd11a-e87e-4c30-b01f-9b0c9c716314.png">

If we were to fix all files at once, it will modify a lot of lines and blame can't be fixed with `.git-blame-ignore-revs`, so unsure of the direction here. It also takes an extraordinary amount of time to do the cleanup locally (with an M1).

I believe this should only be done with new files and touched files. I don't think we can CI this, so it should be used before merging PRs.

**Comment by peppy** [comment]
Generally as a team we've only been applying this as we touch files, and only when things feel really off. I don't think it's worth aiming for anything more at this stage in the project (a lot has changed since 2019 and making sweeping changes just for debatable code quality improvements is unlikely to be a good move).

**Comment by peppy** [comment]
Will just close this for now I think.
