### ISSUE TITLE
Fix handling of keyboard locale

### ISSUE THREAD

**Issue by Tom94** [ppy/osu-framework#252]
Ever since we switched to OpenTK's GameWindow osu! does not respect the layout of my german keyboard (e.g. z and y are swapped).

**Comment by RemieRichards** [comment]
This is an issue in OpenTK itself, there was a proposed fix (https://github.com/opentk/opentk/pull/269) but they decided to stick with ```Key.A``` always matching the american locale.

**Comment by peppy** [comment]
Let's get this fixed, since SDL is progressing so slowly I'm not sure when that will be ready.

@smoogipoo are you against merging in one of the two proposed fix PRs?

https://github.com/opentk/opentk/pull/269
https://github.com/opentk/opentk/pull/665 (probably this one as it is more recent and a smaller change)

**Comment by smoogipoo** [comment]
Are you sure those changes aren’t already in osuTK? Seems weird because we were pretty up to date with everything until the osuTK fork happened (2019?)

Otherwise, sure. I’m not against it.

**Comment by peppy** [comment]
They aren't, if you read the trails they decided not to merge because they were changing too much at the time. I think the current master may have the underlying issues fixed, but switching to that isn't something we are doing anytime soon.

**Comment by peppy** [comment]
Went with the newer one https://github.com/ppy/osuTK/pull/67
