### ISSUE TITLE
Visual / render bug (on resize)

### ISSUE THREAD

**Issue by BlauFx** [ppy/osu-framework#2706]
video: https://streamable.com/ri4d2

**Comment by HoLLy-HaCKeR** [comment]
What is the bug? If you mean the box disappearing, that's probably due to rounding since it's only 1px wide.

**Comment by peppy** [comment]
Please provide code and a question (not just video) if you want actual help.

**Comment by BlauFx** [comment]
```csharp
 [TestFixture]
    public class TestSceneBoxTest : TestScene
    {
        [BackgroundDependencyLoader]
        private void Load()
        {
            Children = new Drawable[]
            {
                new Box
                {
                    RelativeSizeAxes = Axes.Y,
                    Size = new Vector2(1f, 1f),
                    Anchor = Anchor.Centre,
                    Origin = Anchor.Centre,
                },
            };
        }
    }
```

Why is the box disappearing while I'm dragging the window?

**Comment by peppy** [comment]
First thoughts are that this is expected behaviour as you are drawing a quad to the screen and it is between pixels. You are likely expecting anti-aliasing to kick in and show gray pixels rather than nothing. Initial thought is to try adjusting `EdgeSmoothness` and see if this resolves your particular case.

**Comment by BlauFx** [comment]
This resolves my issue
thanks
