### ISSUE TITLE
Very wonky boxes

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#2748]
Am unsure how things got in this state. @smoogipoo any ideas? Never seen anything like this happen before. Draw visualiser looked normal.

https://www.youtube.com/watch?v=XumcpXFb7ic

**Comment by smoogipoo** [comment]
Can't seem to replicate. Can only think of https://github.com/ppy/osu-framework/pull/2718 as a possible cause.

**Comment by smoogipoo** [comment]
Could also verify by turning off front-to-back while in the broken state.

**Comment by smoogipoo** [comment]
Managed to replicate the issue, it seems like `SafeAreaContainer` doesn't correctly support being completely outside the bounds of the parenting `SafeAreaDefiningContainer`.

Here's a repro:

```csharp
public class TestSceneScratch : FrameworkTestScene
{
    public TestSceneScratch()
    {
        Add(new SafeAreaDefiningContainer
        {
            Anchor = Anchor.Centre,
            Origin = Anchor.Centre,
            Size = new Vector2(200),
            Child = new SafeAreaContainer
            {
                Size = new Vector2(100),
                Y = 400,
                Child = new Box { RelativeSizeAxes = Axes.Both }
            }
        });
    }
}
```

Also I highly suspect that SAC won't work if it's being transformed towards a padded edge of the SADC.

@swoolcock pinging because you know this better than me

**Comment by swoolcock** [comment]
Will take a look in a bit.
