### ISSUE TITLE
Exponential and Elastic easing types don't reach correct extremities

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#3015]
Two of the easing types (`Expo` and `Elastic`) provided by the framework don't return correct extreme values when the input (time) is 0 or 1. This can cause some weird visual jumping to occur.

https://www.desmos.com/calculator/h7nhxrctlu

Checking some [other](https://github.com/d3/d3-ease#easeExpIn) [implementations](https://github.com/tweenjs/tween.js/blob/master/src/Tween.js) [of](https://github.com/danro/jquery-easing/blob/master/jquery.easing.js#L74) [easing](http://hackage.haskell.org/package/ease-0.1.0.1/docs/src/Ease.html#expoOut) [curves](http://www.kiwijs.org/api/files/src_animations_tweens_easing_Exponential.ts.html#l43) all seem to use the same equations (or [equivalently broken](https://gillcup.readthedocs.io/en/latest/_modules/gillcup/easing.html#exponential) ones).

Tests available [here](https://github.com/peppy/osu-framework/commit/c009d9b73857fa84dea19883f80f9da7d3de6d6c).

**Comment by bdach** [comment]
*Mathematically* speaking, we could add a linear factor to both so that the jump gets smoothed out over the entire [0,1] interval ([see graph](https://www.desmos.com/calculator/xy0wnueiuv)). Haven't tested how this'll behave numerically on actual floats, however, since the coefficient near the linear factor is astronomically tiny.
