### ISSUE TITLE
Reconsider LocalisedString

### ISSUE THREAD

**Issue by huoyaoyuan** [ppy/osu-framework#3154]
There are 2 concepts of "displaying language" in osu:
- Game metadata. The call site provides 2 variations of text, and the text sprite selects one to display.
- UI text. The call site provides a lookup key and some optional formattable elements. The text sprite displays in the user's language.

Current implementation is written with case 1 in mind. For case 2, I'm strongly against using English text as lookup key due to polysemous words and phases. This means that the 2 cases can have nearly nothing to share at implementation site:
- Case 1, requires Romanized text, Unicode text, and the PreferUnicodeMetadata option.
- Case 2, requires lookup key, format arguments, and the UserLanguage option.

Tagging @smoogipoo .

### My supposed implementation

Rename `LocalisedString` to something like `StringDescriptor` or `LocalisableString` (this struct exists **before** actual localsation), which is accepted by `SpriteText`. It can be constructed by several cases: plain text, Romanized/Unicode, key/arguments.

`SpriteText` doesn't care about it, and passes it directly to localisation manager to ask for a `Bindable<string>`.

Localisation manager decides what to return based on it's type, like current implementation. I suggest to use different classes for different cases, to reduce user option binding overhead.

**Comment by huoyaoyuan** [comment]
Clearifications/highlights for what I suggest to change:
Class rename. It really confuses me.
Don't mix lookup key and Romanized metadata. The lookup key can be provided together with an English fallback.
Replace `LocalisedBindableString` with 3 classes.
Remove the settable interface `ILocalisedBindableString` because the returned `Bindable<string>` may not handle all cases.

**Comment by smoogipoo** [comment]
Seems like a fair direction. I also disliked the name `LocalisedString`. Crowd-in will give us key-value mappings to fulfil case 2.
Keep in mind the 3rd case, which is plain text. Localisation should be transparent to a user of the framework, unless they specifically request it via constructing a `LocalisableString`.

**Comment by UselessToucan** [comment]
By the way, why osu! does not use [GNU/Gettext](https://github.com/VitaliiTsilnyk/NGettext)? It looks quite easy to [use](https://github.com/VitaliiTsilnyk/NGettext#installation-and-usage).

**Comment by bdach** [comment]
As someone who's used gettext before when working with django I advise against using it for our purposes, for the following reasons:

* It uses two formats, one (`.po`) human-editable and one (`.mo`) not. The latter one is actually used by consumer applications, therefore introducing a new tooling step.
* `.po` files are absolutely giant blobs (at least it's one file per language, not altogether), barely human-editable due to an antiquated format, without sane logical grouping of phrases (best you get is line/column of the string in code), and not viable for collaboration due to a high risk of an awful lot of merge conflicts. I also remember struggling with the tool mangling my translations since it was doing weird things with word wrapping.
* Would either need a separate repo for localisations or introduce noise to the existing one when submitting crowdsourced translations.
* crowdin has been battle-tested web-side and I assume it does its job well enough to not warrant exploring alternatives.

**Comment by peppy** [comment]
crowdin is not a format itself, but can be used to export to our format of choice, for what it's worth. gettext is [one of the supported formats](https://support.crowdin.com/file-formats/po/).

**Comment by huoyaoyuan** [comment]
In addition, I'd like to allow user to customize texts, as a part of UI customization.

Xliff is the "native" format of .NET, but doesn't support hot update.

**Comment by peppy** [comment]
Should be safe to close this one, with the recent refactor (https://github.com/ppy/osu-framework/pull/3157).
