### ISSUE TITLE
Decouple selection highlighting logic from Caret

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-framework#3210]
- Dependency for #1618 

While I've been working on supporting multi-line textbox, I've realized the logic behind highlighting selected text after supporting multi-line made the `TextBox` a bit more convoluted, so I chose to abstract selection highlighting logic.

### NOTE: I will implement this, just asking questions on implementation here

- What should the name of the component be? I prefer `Highlighter` since it's a component that adds a list of highlight lines with calculated position and size.
- Should the component minimally support only required features to work with `TextBox`? there are other features that could be added to the component like:
  - Allow highlighting different areas at once, something like:
    ```csharp
    AddHighlight(0, 2); // highlight area from index 0 with length 2
    AddHighlight(4, 2); // highlight area from index 4 with length 2 (previous area is still highlighted)
    ClearHighlights(); // Clears all highlighted areas
    ```
  - Invalidate highlights on any change in the source container or its children from positioning and sizes.

**Comment by iiSaLMaN** [comment]
ping @peppy @smoogipoo for feedback.

**Comment by smoogipoo** [comment]
I'm not sure such a huge abstraction is necessary. In advanced cases like multiple highlights, you're essentially describing functionality that a "rich" textbox would serve - multiple cursors, per-character colouring, etc.

Imo TextBox and MultilineTextBox should be very simple implementations, serving just the stated roles to their most simplest degree. I'm not sure if `MultilineTextBox` should even exist, even. For example WinForm's `TextBox` and WPF's equivalent both support multiline as part of their `TextBox` implementation.

**Comment by iiSaLMaN** [comment]
> I'm not sure such a huge abstraction is necessary. 

If I understand correctly, as @peppy mentioned in https://github.com/ppy/osu-framework/issues/1618#issuecomment-396134645
![image](https://user-images.githubusercontent.com/22781491/73449725-dcecdf80-4374-11ea-9122-0fe0f55c9a06.png)
stating that the `TextBox` is already complex, and I absolutely agree given the [logic I've written](https://gist.github.com/iiSaLMaN/f9cc1e58b582fb334bd686ac7ea4d191) and tried to make as simple as possible. (not sure if a bug-prone component counts as simple)

> In advanced cases like multiple highlights, you're essentially describing functionality that a "rich" textbox would serve - multiple cursors, per-character colouring, etc.

Keep in mind this component could be used for purposes outside of `TextBox`, like highlighting 2 texts of a `TextFlowContainer` at the same time.

> Imo TextBox and MultilineTextBox should be very simple implementations, serving just the stated roles to their most simplest degree. I'm not sure if `MultilineTextBox` should even exist, even. For example WinForm's `TextBox` and WPF's equivalent both support multiline as part of their `TextBox` implementation.

`TextBox` is currently complex, adding `MultilineTextBox` features to it would make it beyond how complex it is, I would agree if we could do more abstractions that could potentially make `TextBox` very simple to deal with, otherwise merging the two components is really not a good idea.

**Comment by frenzibyte** [comment]
Closing as I think such questions are better suited in a pull request rather than a dedicated issue thread.
