### ISSUE TITLE
InvalidOperationException when pressing a key in a dropdown menu when settings SearchTextBox isn't empty

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu-framework#3498]
**Describe the bug:**
- Open the settings panel
- Search for an option with a dropdown using the `SearchTextBox`
- Open the dropdown
- Press any key, the game will throw an `InvalidOperationException`

**Screenshots or videos showing encountered issue:** [Video](https://drive.google.com/file/d/1cNvBwZNV-J8KYeGqjC8jmm2SpsHp7Gkq/view?usp=sharing)

**Logs:** [runtime.log](https://github.com/ppy/osu/files/4558015/runtime.log)

**Comment by iiSaLMaN** [comment]
Upon simple reading through where this failed, this is happening due to `DropdownMenu.OnKey()` expecting there to be one item selected in the dropdown if it contains at least one. 

Wile this is related to and will be fixed with https://github.com/ppy/osu/issues/8912#issuecomment-621793535, there are valid dropdowns with items but nothing currently selected, will look into fixing this.
