### ISSUE TITLE
Controlling font for FrameworkAction dialogs

### ISSUE THREAD

**Issue by kotx** [ppy/osu-framework#3520]
The first font that is added is automatically used for the whole game. Some fonts do not work well with FrameworkActions (the global statistics with Ctrl+F2, etc). I'd like to be able to preserve or set a separate font for said dialogs.

**Comment by smoogipoo** [comment]
Imo best is to preserve the fonts, but exposing a `ToolFont` property from `Game` may be a reasonable alternative.

**Comment by kotsh** [comment]
I would keep it too, but the font I'm using is a bit too
 big so text is either truncated or wrapped. AFAIK there's no way of customizing or resizing the tool window either..?
![image](https://user-images.githubusercontent.com/33439542/81036780-37567a00-8e55-11ea-88aa-da47a5eb01c6.png)

**Comment by peppy** [comment]
Exposing a ToolFont sounds like a good path forward. If anyone's looking for a low hanging fruit, this may be your chance.

**Comment by harshavb** [comment]
Rather than exposing a ToolFont, it should be preferable to just make it so class ToolWindow and all implementations of ToolWindow only use a FrameworkFont, since that is already the case everywhere except for two instances in TextureVisualizer.cs. The issue actually seems to exist because FrameworkFont does not work as intended in any case since Roboto and RobotoCondensed aren't implemented by default in Game.cs. However, I cannot get FrameworkFont to work while still allowing custom fonts to be defined for all non ToolWindow text unless the custom font is added _after_ Roboto and RobotoCondensed are added, which is an issue since that would mean developers would have to add in Roboto and RobotoCondensed themselves for every project. I am unsure how to continue from here, but it would likely require some sort of reimplementation of either AddFont(), addFont(), or FontUsage().
