### ISSUE TITLE
DrawSizePreservingFillContainer not behaving as expected when parent is padded

### ISSUE THREAD

**Issue by Jeremiidesu** [ppy/osu-framework#3592]
[Here's a gist](https://gist.github.com/Jeremiidesu/25820290f3df953b71f4dfac77530345) with what should be a minimal reproducible example.

When the parent container has padding applied, a child of the DSPFC whose absolute size matches the TargetDrawSize (shown here in transparent blue) overflows from the container's size (shown here in red)
![image](https://user-images.githubusercontent.com/20820425/83362546-72839480-a392-11ea-8d62-2f21a8419e1f.png)

**Comment by bdach** [comment]
In this use case the `DrawSizePreservingFillContainer` does not do what it is expected to due to taking the parent's draw size directly and not accounting for padding:

https://github.com/ppy/osu-framework/blob/2d2ec02f5551af99703b028eb386875c83071d59/osu.Framework/Graphics/Containers/DrawSizePreservingFillContainer.cs#L47

As discussed on Discord, the two variants that would resolve the problem for this use case would be to either use the DSPFC's own `DrawSize`, or `Parent.ChildSize`, but since that component's code has been seemingly untouched since its inception I'm not 100% sure whether this use case is intended for DSPFC. If not, the proper way to do this might be to add an extra container for padding.

**Comment by frenzibyte** [comment]
In my opinion, whether it's intended or not to always fill to the parent size (still broken since the container will be moved by the top & left padding), I would be in favour of removing this limitation, existing usages that take advantage of that must be fixed by an extra container.

Also correcting @bdach's comment above, `DrawSize` will fix not only this case, but other potential cases like:
```csharp
new DrawSizePreservingFillContainer
{
     Size = new Vector2(0.6f);
}
```

So it is best to use `DrawSize` instead of `Parent.ChildSize`.

**Comment by bdach** [comment]
@frenzibyte Note the xmldoc on the class:

https://github.com/ppy/osu-framework/blob/2d2ec02f5551af99703b028eb386875c83071d59/osu.Framework/Graphics/Containers/DrawSizePreservingFillContainer.cs#L10-L13

The DSPFC's size should not be relevant in any case in light of it, so I actually retract the suggestion of using its own `DrawSize`. In my eye at this point it's a question of whether the padding should be taken into account when filling the parent.

**Comment by frenzibyte** [comment]
> @frenzibyte Note the xmldoc on the class:
> 
> https://github.com/ppy/osu-framework/blob/2d2ec02f5551af99703b028eb386875c83071d59/osu.Framework/Graphics/Containers/DrawSizePreservingFillContainer.cs#L10-L13
> 
> The DSPFC's size should not be relevant in any case in light of it, so I actually retract the suggestion of using its own `DrawSize`. In my eye at this point it's a question of whether the padding should be taken into account when filling the parent.

Right, In this case I think it's fine to take the parent's padding into account and use `Parent.ChildSize` but I would highly recommend overriding `Size` setter and throwing there to avoid anyone reporting issues about such cases.
