### ISSUE TITLE
How remove Textures Filters?

### ISSUE THREAD

**Issue by clyde-not-found** [ppy/osu-framework#3782]
I started using osu! Framework and learning how to use sprites on it, but when I add one to the app it gets a little blurry. Does anyone know how to remove this?

![image](https://user-images.githubusercontent.com/49321124/89134423-874be800-d4fb-11ea-9c95-51f09103aca8.png)

**Comment by peppy** [comment]
I believe the current logic requires you to make your own custom texture store (and use it instead of `Game.Textures` where required).

```csharp
var noFilterTextures = new TextureStore(Host.CreateTextureLoaderStore(new NamespacedResourceStore<byte[]>(Resources, @"Textures")), filteringMode: All.Nearest);
           
noFilterTextures.Get("my-pixel-texture");
```

You can see a real-world example in the template game: https://github.com/ppy/osu-framework/blob/master/osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/FlappyDonGameBase.cs#L25-L28

**Comment by clyde-not-found** [comment]
Thank you so much I managed to remove the filter!
