### ISSUE TITLE
Characters can't be deleted when holding modifier keys

### ISSUE THREAD

**Issue by Pennek** [ppy/osu-framework#3954]
Characters can't be deleted inside the song setup screen after they have been added, if the user is still holding `SHIFT` or `CAPS LOCK`. If `CTRL` is held, characters can't be entered or deleted. After the keys are released, characters can be entered/deleted once again.

I'm guessing `CTRL` doesn't work because keyboard input is overwritten by whatever handles osu!direct searches, as `CTRL`+`D` brings up osu!direct.

osu!lazer version: 2020.1005.0

**Comment by Susko3** [comment]
>Characters can't be deleted [...] if the user is still holding SHIFT or CAPS LOCK

With https://github.com/ppy/osu-framework/pull/4485, backspace while shifted now works as expected. <kbd>Shift</kbd>+<kbd>Del</kbd> still doesn't delete.
As for caps lock, it appears that it now works, I can hold caps lock and delete characters. If it's still a problem, please report back with more information on your setup.

> If CTRL is held, characters can't be entered or deleted.

This is expected behavior to me, <kbd>Ctrl</kbd>+<kbd>some key</kbd> is reserved for keyboard shortcuts, and doesn't enter text in any application I've tested (eg. Notepad, Word, Firefox).

Also, <kbd>Ctrl</kbd>+<kbd>BackSpace</kbd>/<kbd>Del</kbd> deletes the previous/next word. So deleting works.

**Comment by smoogipoo** [comment]
I can't seem to repro this, let's call it closed until it's reported again.
