### ISSUE TITLE
Reconsider whether bindable unbinding should consider properties

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#4014]
Auto-properties will have their backing fields picked up by the field unbinds, so this will only affect properties that reference external bindables. I think that's pretty dodgy to do in general.

**Comment by OliBomby** [comment]
I made it so properties would no longer get picked up for unbinds and there was just one test that started failing. `TestUnbindOnDrawableDisposeProperty` in BindableBindingTest.cs. 

This test gives an external binding to the drawable and then disposes it, removing the binding. I think this test is actually asking for wrong behaviour because after disposing the drawable, the binding outside the scope of the drawable will no longer work and `valueChanged` will no longer update.

**Comment by smoogipoo** [comment]
That test would have to be removed, yup.
