### ISSUE TITLE
Game crashes on startup with latest update

### ISSUE THREAD

**Issue by ben9583** [ppy/osu-framework#4041]
I'm working on a game using osu-framework ([harshavb/piously](https://github.com/harshavb/piously)), and the most recent update (2020.1127.1) crashes the game upon initialization. This does not happen with version 2020.1120.0; the game runs as intended on that version.

I'm running this on MacOS Catalina 10.15.7, but this issue occurs on Windows as well.

Error (I'm not running this with SDL, so I don't understand why there are all the references to it):
Process terminated. A callback was made on a garbage collected delegate of type 'SDL2-CS!SDL2.SDL+SDL_EventFilter::Invoke'.
   at SDL2.SDL.SDL_ShowWindow(IntPtr)
   at SDL2.SDL.SDL_ShowWindow(IntPtr)
   at osu.Framework.Platform.SDL2DesktopWindow+<>c__DisplayClass67_0.<set_Visible>b__0()
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Platform.SDL2DesktopWindow.Run()
   at osu.Framework.Platform.GameHost.Run(osu.Framework.Game)
   at Piously.Desktop.Program.Main(System.String[])

<img width="1020" alt="Screen Shot 2020-11-27 at 9 23 09 AM" src="https://user-images.githubusercontent.com/16968917/100530400-d73b7280-31ae-11eb-8820-0094013c5a6a.png">

**Comment by jai-x** [comment]
As of merge https://github.com/ppy/osu-framework/pull/3996, `osu-framework` now uses the SDL window backend by default.

The specific crash that you have encountered has been fixed in https://github.com/ppy/osu-framework/pull/4040, but this has only been recently merged into `master` and is not yet available in a versioned release.

As a workaround, you can launch using the `--tk` argument to use the old OpenTK window backend until the the new framework version is released.

**Comment by peppy** [comment]
Said release was pulled shortly after it went live; please use 1129 instead (publishing now).

**Comment by ben9583** [comment]
Thank you for the help; I will go ahead and update.
