### ISSUE TITLE
Window size doubles everytime program is relaunched in SDL

### ISSUE THREAD

**Issue by ben9583** [ppy/osu-framework#4088]
Specs:
16-inch MacBook Pro with higher-DPI retina display
Intel core i9-9980HK, AMD Radeon Pro 5500m
MacOS Catalina 10.15.7

On my display, there's a bug in which, if the window does not take up the maximum space it is allowed (screen display minus the dock at the bottom), the next time I launch the program, the window doubles in size, but the content of the program takes up only the bottom left quadrant of the screen as pictured below:

About to close the program with this resolution:
<img width="1792" alt="Screen Shot 2020-12-10 at 11 04 35 AM" src="https://user-images.githubusercontent.com/16968917/101811720-aa089180-3ad7-11eb-9093-b77e13453753.png">

Relaunching the program looks like this (changed background to yellow is normal):
<img width="1792" alt="Screen Shot 2020-12-10 at 11 04 49 AM" src="https://user-images.githubusercontent.com/16968917/101811756-b7258080-3ad7-11eb-9a78-13b3d5447bd0.png">

This is an issue with all `osu-framework` games, including osu!:
<img width="1792" alt="Screen Shot 2020-12-10 at 11 25 36 AM" src="https://user-images.githubusercontent.com/16968917/101813872-84c95280-3ada-11eb-9195-edec01ae76c2.png">
 
My guess is that, although the program content correctly accounts for my retina display's layout of 2x2 physical pixels per logical pixel, the window assigns the window size in physical pixels to be the size in _logical pixels_, doubling its size.

When the window is resized at all, the program realizes its mistake and corrects the resolution so the program takes up the entire window. When the window reaches the maximum space it is allowed, it no longer tries to double in size and therefore doesn't display this bug, which I why I had never caught it before when I tested the solution for issue #4044 since I work at that resolution by default.

**Comment by bdach** [comment]
As far as I can see, the size is stored to config here:

https://github.com/ppy/osu-framework/blob/abdda4ab5d3ffcad69c539a88e5aec6e12753b45/osu.Framework/Platform/SDL2DesktopWindow.cs#L469-L482

and read from config here:

https://github.com/ppy/osu-framework/blob/abdda4ab5d3ffcad69c539a88e5aec6e12753b45/osu.Framework/Platform/SDL2DesktopWindow.cs#L970-L977

Does make sense that this could mismatch, seeing that the read value comes from `SDL_GetDrawableSize` (which is [the size of the render target in "physical" pixels](https://wiki.libsdl.org/SDL_GL_GetDrawableSize), so @2x or whatever the scale is), and the set uses `SDL_SetWindowSize` (which is [the size in screen coordinates/"logical" pixels](https://wiki.libsdl.org/SDL_GetWindowSize))

Can't test the above hypothesis due to no hardware, however.

**Comment by ben9583** [comment]
It seems as through changing `SDL.SDL_SetWindowSize(SDLWindowHandle, Size.Width, Size.Height);` to `SDL.SDL_SetWindowSize(SDLWindowHandle, (int)(Size.Width / 2), (int)(Size.Height) / 2);` corrects the window size (I'm not sure how to implement Scale since dividing by Scale doesn't seem to make a difference). However, the input issue from #4044 is present until the window is resized.

**Comment by frenzibyte** [comment]
@bdach That is quite correct, the `sizeWindowed.Value` is having the physical size instead of the logical one. will solve that.
