### ISSUE TITLE
Shift is before ctrl in KeyCombination's ReadableString

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-framework#4153]
![osu!_Si6KfpAKHO](https://user-images.githubusercontent.com/35318437/104784760-d601dd00-573d-11eb-9da5-c8f8776b18e2.jpg)

**Comment by bdach** [comment]
This uses the raw `Keys` order now:

https://github.com/ppy/osu-framework/blob/795022ff055083c95b80e0364e504ff876d387ee/osu.Framework/Input/Bindings/KeyCombination.cs#L146

The way to go would probably be to move `OrderAttribute` from game and annotate modifiers so that they print in the correct order (as opposed to "just changing the enum values", which would break backwards compat.
