### ISSUE TITLE
Move CompositeDrawable and Drawable Lifecycle methods to a base class

### ISSUE THREAD

**Issue by sr229** [ppy/osu-framework#4281]
This is a continuation of our discussion has been about moving some of the lifecycle methods existing in `Drawable` and move it to `Component`, and introduce a new class, `Composite<T>` - based from `CompositeDrawable`.

## Moving `Drawable`s lifecycle method to `Component`

One of the things we discussed is moving `Drawable`'s lifecycle to `Component`. This has been planned already for a while now so the refactoring needed would be to move all lifecycle handling methods to `Component`, and have `Drawable` inherit `Component` instead.

## The `Composite<T>` class

@smoogipoo raised also a new idea regarding the lifecycle rewrite, this time, focusing on `CompositeDrawable`. He proposed that something like `Composite<Drawable>` would be nice. While it hasn't been investigated thoroughly, `Composite<T>` would be something that is also included in this proposal as it's also within the scope of the lifecycle refactoring.

However, @frenzibyte raised an issue about the prospect of duplicating code if someone were to use `Composite<T>`, so a better approach would need to be investigated as well so we don't end up requiring people to copy over everything from `T`.

## TODO

The proposal would be focusing on the following parts:

- [ ] Move all lifecycle into `Component` from `Drawable`.
- [ ] Implement `Composite<T>` in a way we can reduce, if not prevent, code duplication.

**Comment by smoogipoo** [comment]
If you want to go with my idea you will need to start composing via interfaces, like so:

```csharp
public interface IComponent
{
    void UpdateSubTree();
}

public interface IComposite<out TComponent> : IComponent
    where TComponent : IComponent
{
    IReadOnlyList<TComponent> InternalChildren { get; }
}


public abstract class Component : IComponent
{
    public virtual void UpdateSubTree()
    {
    }
}

public class Composite<TComponent> : Component, IComposite<TComponent>
    where TComponent : IComponent
{
    public IReadOnlyList<TComponent> InternalChildren { get; set; }

    public override void UpdateSubTree()
    {
        base.UpdateSubTree();

        foreach (var c in InternalChildren)
            c.UpdateSubTree();
    }
}

public class Drawable : Component
{
}

public class CompositeDrawable : Drawable, IComposite<Drawable>
{
    private readonly Composite<Drawable> composite = new Composite<Drawable>();

    protected internal IReadOnlyList<Drawable> InternalChildren
    {
        get => composite.InternalChildren;
        set => composite.InternalChildren = value;
    }

    public override void UpdateSubTree()
    {
        base.UpdateSubTree();
        composite.UpdateSubTree();
    }

    IReadOnlyList<Drawable> IComposite<Drawable>.InternalChildren => InternalChildren;
}
```
Just a rough example.
Just a quick example, this is a huge task.

**Comment by sr229** [comment]
Working on this for a while though I may have encountered a little bit of a problem, would it be technically feasible to replace `CompositeDrawable` as `Composite<Drawable>`. I haven't opened the code for it but I assume a lot of `CompositeDrawable` could be just turned into its own generic class.

**Comment by bdach** [comment]
Lacking context to reply accurately (no idea what the "problem" is there), but one thing I can say for sure is that would be a huge breaking change, so just replacing would have to be done with a lot of care. You definitely would want to do `CompositeDrawable : Composite<Drawable>` at least for a while, even if it were to be an empty implementation (which I honestly find unlikely, there's some drawable-specific stuff in there). The framework has a 6-month transition policy for breaking changes, and I'd argue this is one of the cases when even a longer one would be warranted.

**Comment by sr229** [comment]
> Lacking context to reply accurately (no idea what the "problem" is there), but one thing I can say for sure is that would be a huge breaking change, so just replacing would have to be done with a lot of care. You definitely would want to do `CompositeDrawable : Composite<Drawable>` at least for a while, even if it were to be an empty implementation (which I honestly find unlikely, there's some drawable-specific stuff in there). The framework has a 6-month transition policy for breaking changes, and I'd argue this is one of the cases when even a longer one would be warranted.

That's no exception I'll still keep `CompositeDrawable`, though I wonder if we can rather simplify the implementation since I think it should be much cleaner just doing `Composite<Drawable>` than worrying that doing composite drawables should be handled specially, but I was much more worried how much Drawable-specific functions and methods are there that cannot be warranted to be simplified.

**Comment by bdach** [comment]
A `Composite<T>`, as I gather, would just group `Component`s and hook them into the game loop in the same manner as `CompositeDrawable` does, and nothing more. Possibly manage lifetime, too, if `Composite`s will have lifetime. You cannot however wholly replace `CompositeDrawable` with a `Composite<Drawable>`, because the former is more specific. Drawable-specific things, like `CornerRadius`, or depth, or autosize, etc., that are implemented on a `CompositeDrawable` level make zero sense for `Composite<T>`.

**Comment by sr229** [comment]
Just some progress update: we were able to completely port all the required methods in `Component`, [Which you can view in its entirety here](https://github.com/vignette-project/osu-framework/blob/vignette/primitives/osu.Framework/Primitives/Component.cs), however we're not so entirely sure if `Transforms` should also be moved to `osu.Framework.Primitives`.

**Comment by bdach** [comment]
Transforms are not necessarily bound to drawables, they can be used to drive arbitrary values (and there are a few usages of this game-side, like the rolling counter). So transforms could live in `Component` I think.

**Comment by sr229** [comment]
> Transforms are not necessarily bound to drawables, they can be used to drive arbitrary values (and there are a few usages of this game-side, like the rolling counter). So transforms could live in `Component` I think.

Regarding this, we did move a lot of Transforms to `Primitives` but we'll need to keep some certain classes in since they're intertwined with the Drawable and Graphics logic itself, otherwise, everything else should be more tidy.

**Comment by LeNitrous** [comment]
After some additional research and discussion between myself and @sr229, we have decided to point out 3 main objectives in our upcoming PR.
1. Reduce the object size of non-drawables by splitting `Drawable` and `Component`.
2. Allow all `Component`s to exist in the hierarchy.
3. Restructure the inheritance tree as shown in the diagram below:

![image](https://user-images.githubusercontent.com/20495991/122860351-236b2180-d350-11eb-864f-c75722066205.png)

This is just a rough outline of what we will do in the meantime. Please let us know if there are questions with this approach.

**Comment by peppy** [comment]
In isolation that diagram looks correct. The important thing about moving forward with this is going to be breaking the tasks up into smaller ones. You haven't mentioned anywhere how you plan on tackling this - if you can give any insight here before getting too deep we may be able to give you more guidance.

**Comment by frenzibyte** [comment]
One thing which has already been stated somewhere above is that `Component`s should have the full ability to transform properties, thus `Component` should inherit `Transformable`, rather than the opposite.

**Comment by sr229** [comment]
> In isolation that diagram looks correct. The important thing about moving forward with this is going to be breaking the tasks up into smaller ones. You haven't mentioned anywhere how you plan on tackling this - if you can give any insight here before getting too deep we may be able to give you more guidance.

We decided to split this into two parts, getting `Component` in a state it's ready for initial use, that means, this will get the foundation right by the first PR, then the second PR will be dealing with inheritance and other outliers in the task.

**Comment by sr229** [comment]
> One thing which has already been stated somewhere above is that `Component`s should have the full ability to transform members, thus `Component` should inherit `Transformable`, rather than the opposite.

This is a given since in the current rev on our tree, `Component` has `Transformable`. We want to keep most of the essential stuff in `Component` as much as possible.

**Comment by LeNitrous** [comment]
> One thing which has already been stated somewhere above is that `Component`s should have the full ability to transform members, thus `Component` should inherit `Transformable`, rather than the opposite.

I haven't found a use case for a `Component` to use transforms. If there are such use cases please let us know and we'll need to figure out how to proceed with this.

**Comment by peppy** [comment]
Have you tested your changes against something like osu!? You will find that `AudioComponent` or `AudioContainer` already uses this.

**Comment by LeNitrous** [comment]
I have reverted the edit and will continue from here.

> One thing which has already been stated somewhere above is that `Component`s should have the full ability to transform members, thus `Component` should inherit `Transformable`, rather than the opposite.

I still don't see why a `Component` should inherit `Transformable` as most use cases of transforms manipulate properties that have some sort of feedback (i.e. a `Drawable`'s colour or an `AudioComponent`'s volume). However since `Transformable` is originally `abstract` to begin with, I'll keep it as is and instead make it inherit `Component`. The new diagram should reflect that shown below:

![image](https://user-images.githubusercontent.com/20495991/122866147-13583f80-d35a-11eb-8a56-d80091778286.png)

Generally speaking this is what each class should do:
1. `Component` - The core class of the framework. Everything that should exist in the scene hierarchy must inherit from this. This class handles lifetime and bindable management.
2. `Transformable` - Any components that require transforms and easing is handled by this class. It must be inherited.
3. `Composite` - A `Component` that allows child `Component`s to reside inside it.
4. `Drawable` - A `Component` capable of drawing something on the screen.
5. `AudioComponent` - A `Component` capable of providing audio to the scene.
6. `Container` - A `Drawable` that allows other child `Drawable`s (and possibly `Component`s as well?). Looking at the diagram, it implements `IContainer` which then also implements `IComposite`. This is due to a limitation in C# that we are not allowed to do multiple inheritance.

**Comment by peppy** [comment]
You'll probably also want to include `CompositeDrawable` in your diagram as that's a very common one which may bring implementation complexities with it.

**Comment by frenzibyte** [comment]
It's not well-known that components should inherit `Transformable` rather than `Component` for transforms, it was always either you inherit a `Drawable` or its subclasses for drawable content and otherwise, or `Component` for non-drawable but still access to BDL / lifetime / transforms.

Also that way you're still limiting `Composite`s from the ability to transform properties as well, I'm pretty sure that might be useful in some way at some point.

I'm wondering if there are any issues with just making `Component` inherit `Transformable`, because it looks to make sense that way and is how it usually should be here, I don't see any reason for flipping it.

**Comment by peppy** [comment]
I believe the goal is to reduce the size of components (so they don't carry the `Transformable` overhead). But at least as a first step, I agree that's best to avoid considering. A future pass may move transformable pieces out into composition rather than inheritance, which will likely suit it much better.

**Comment by LeNitrous** [comment]
@sr229 and I attempted to rewrite this but have faced a lot of issues along the way (mostly because of the inheritance-based paradigm it uses). We stepped back and thought of expanding the scope a bit more to root out the underlying issue and make it more than just a band-aid fix.

Here is the diagram proposing the new structure:
![image](https://user-images.githubusercontent.com/20495991/132605270-532c6573-b5e9-4ffb-a733-73492860ed38.png)
### Considerations:
1. The parent and children references are now done by numeric IDs.
2. Everything in the scene hierarchy is referred to as entities and must implement `IEntity` which contains properties about its ID and the parent's ID.
3. Everything that has children is an `IComposite<T>` and contains a list if IDs of its children entities.
4. All entities present in the game are stored in a single one-dimensional collection.
5. There will be interfaces implemented for each kind of thread declaring its capabilities.
    - for instance, `IUpdateable` which contains properties about an entity lifecycle is ran on the update thread and `IDrawable` for the draw thread.

**Comment by bdach** [comment]
Bit hard to address the above seeing that the issues you've apparently faced aren't described at all in any detail. I'd like to know what they were to be able to try and see why these structural changes are being proposed.

**Comment by LeNitrous** [comment]
1. Initially the first diagram did not take into account how tightly coupled `Drawable` was to how it was used in `GameHost`. By splitting it to interfaces by its capabilities, it allows us to compose how an object is defined.
2. The scene hierarchy and the way it is written (and the way if it was rewritten as proposed in the previous diagram) will only allow drawables to exist causing oddities like `osu.Framework.Graphics.Audio` to even happen. By making everything an `IEntity`, anything that implements the interface can exist in the scene hierarchy. This fully eliminates `DrawableTrack` and `DrawableSample` and directly allowing `Track` and `Sample` to co-exist with drawables and components.
3. We were originally going to remove `CompositeDrawable` in favor of `Composite<T>`. However making it generic was simply not possible due to the limitations of the inheritance chain and generics. By making the parent-child relationships referenced by numeric IDs in a many-to-one relationship. Since child and parent is always an `IEntity` we can simply get its type back by casting.

Upon looking into it more, it also doesn't take into account how dependency injection and bindable management is handled. I have updated the diagram to include a new `Entity` class as a base class that handles dependency injection and bindable management.

![image](https://user-images.githubusercontent.com/20495991/132636038-a660ebb5-e7cf-4a41-8b79-c48e1b11032b.png)

However I'm still unsure about the relationship with `IComposite<T>` to `Composite<T>` and `Container<T>` as they will have shared code specifically regarding updating children.

**Comment by frenzibyte** [comment]
I still fail to understand how this is required to address the issue of `Component` inheriting `Drawable` rather than the opposite.

And I had believed that the way would simply be to move the lifecycle, BDL, etc. out of `Drawable` and into `Component`, and making a `Composite` class similar to the structure @smoogipoo proposed in https://github.com/ppy/osu-framework/issues/4281#issuecomment-799899957, and finally flip the inheritance of `Component`.

> 1. Initially the first diagram did not take into account how tightly coupled Drawable was to how it was used in GameHost. By splitting it to interfaces by its capabilities, it allows us to compose how an object is defined.

Would that currently be an issue, `GameHost` should only be dealing with a root `Container` which should have the properties of drawing and updating?

> 2. The scene hierarchy and the way it is written (and the way if it was rewritten as proposed in the previous diagram) will only allow drawables to exist causing oddities like osu.Framework.Graphics.Audio to even happen. By making everything an IEntity, anything that implements the interface can exist in the scene hierarchy. This fully eliminates DrawableTrack and DrawableSample and directly allowing Track and Sample to co-exist with drawables and components.

Having `AudioComponent` inherit from `Component` and make its subclasses (`Track` and `Sample`/`SampleChannel`) co-exist with drawables sounds like it may be a decent change and reduce somewhat of duplicated logic in there, but all of that should be irrelevant from both this issue thread and the goal of flipping the `Drawable`/`Component` inheritance, and to be addressed at a later point after the inheritance flip happens.

> 3. We were originally going to remove CompositeDrawable in favor of Composite<T>. However making it generic was simply not possible due to the limitations of the inheritance chain and generics. By making the parent-child relationships referenced by numeric IDs in a many-to-one relationship. Since child and parent is always an IEntity we can simply get its type back by casting.

It was probably mentioned already, but `CompositeDrawable` shouldn't just be removed in favour of `Composite<Drawable>`, I don't even see how that's feasible with the aforementioned `Composite` structure proposal.

All in all I think these structural changes are not required for this issue thread and can have a separate "code quality" issue thread tracking it instead, once this issue thread gets addressed and the `Component` inheritance flip happens.

**Comment by sr229** [comment]
> And I had believed that the way would simply be to move the lifecycle, BDL, etc. out of Drawable and into Component, and making a Composite class similar to the structure @smoogipoo proposed in #4281 (comment), and finally flip the inheritance of Component.

We have tried multiple times and just "flipping" the inheritance doesn't really fix anything, unless it constitutes a re-architecting of the system, it still bears the same problem, it doesn't solve any of the issues this proposal is trying to solve. If we cannot remove `CompositeDrawable`, that's considered a failure of this proposal's rewrite. The current architecture requires everything is a drawable, and that's really not acceptable.


I do agree we have veered off from the original proposal, but as soon as we started the rewrite, we started encountering issues on how it's being written, so this evolved into a simple rewrite into what is fundamentally changing how everything works in the framework.


This is pretty difficult to explain in words so a proof of concept will be written to better represent what we want to achieve, which we plan to do around this December or so.

**Comment by bdach** [comment]
I see no point discussing this proposal further until a proof of concept is developed as it's well inside the land of make-believe. What is being proposed is essentially rewriting the framework into an ECS system. I'm not sold that the core ideas will hold up at scale (especially things like a global entity list) and if breaking changes are prohibitively large you will likely face major opposition to upstreaming your proposals, because I don't think anyone is interested in essentially rewriting lazer from the ground up, too.

**Comment by sr229** [comment]
After much discussion we decided not to proceed with the rewrite due to the large impact of the rewrite (involving rewriting Lazer, which is infeasible for the scale of our team), we will be closing this. However, for any prospective contributors who wants to resume our work, I hope our findings will help you.
