### ISSUE TITLE
Config value will display as float.MAX_VALUE if its value exceeds max value

### ISSUE THREAD

**Issue by PercyDan54** [ppy/osu-framework#4398]
**Describe the bug:** 
Config value will display as float.MAX_VALUE if it's value is greater than the max defined in `ConfigManager`

Edit: In the config file its value is still the max value, just display error, and clicking restore to default doesn't work
![image](https://user-images.githubusercontent.com/50285552/115942864-ed8bf700-a4de-11eb-9719-8646f82b19d4.png)

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/50285552/115942688-0cd65480-a4de-11eb-8557-9052fa96ceda.mp4

**osu!lazer version:** 
local debug

**Comment by peppy** [comment]
please provide an isolated framework test case to show that this isn't something local to whatever your project is

**Comment by PercyDan54** [comment]
> please provide an isolated framework test case to show that this isn't something local to whatever your project is

Here's a failing test

```
  Expected: 1.0f
  But was:  <2.0>

  Stack Trace:
     at osu.Framework.Tests.Configuration.FrameworkConfigManagerTest.TestMultipleBindExceedMax() in D:\Dev\OSU\osu-framework\osu.Framework.Tests\Configuration\FrameworkConfigManagerTest.cs:line 69
```

``` C#
        [Test]
        public void TestMultipleBindExceedMax()
        {
            using (var storage = new TemporaryNativeStorage(new Guid().ToString()))
            {
                using (var configManager = new FrameworkConfigManager(storage))
                {
                    var bindable = configManager.GetBindable<float>(FrameworkSetting.VolumeUniversal);
                    var bindable2 = new Bindable<float>();
                    bindable2.BindTo(bindable);
                    bindable2.Value = 2;
                    Assert.AreEqual(1.0f, bindable);
                    Assert.AreEqual(1.0f, bindable2);
                }
            }
        }
```

**Comment by frenzibyte** [comment]
I have no clue how this is related to the above, but I can answer you on this one:

this is a bug known regarding binding `BindableNumber`s with `Bindable`s, it may be an allowed thing and get fixed by https://github.com/ppy/osu-framework/pull/4069, or it may just not be allowed at all and you'll get an exception thrown for doing so.

what you should do is `bindable.GetBoundCopy()` instead.

(also not sure if you're aware but that assertion is not correct, you should be asserting with `bindable.Value` not `bindable`)
