### ISSUE TITLE
GitHub actions CI doesn't output inspectcode errors

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#4502]
See for example https://github.com/ppy/osu-framework/runs/2790302770

The ReSharper job outputs an error to the console but the workflow did not fail.

**Comment by bdach** [comment]
The [current action](https://github.com/glassechidna/resharper-action) used for reporting inspectcode results does not seem to exit with a non-zero exit code or in any way try to set the status of the check to indicate failure, it just parses the xml report and prints it in a particular format that is picked up by github to show the inline annotations.

There is [another action](https://github.com/muno92/resharper_inspectcode), recently created, that may be closer to what is required, but I have... limited trust towards it. It may just be better to roll our own, if we do decide to continue with actions, which I'm less and less convinced about as time goes because there are important features missing.

**Comment by bdach** [comment]
Another thing that occurred to me is extending/forking nvika to provide this functionality. The project [already seems to be structured in a way amenable to it](https://github.com/laedit/vika/blob/master/src/NVika/BuildServers/AppVeyor.cs). May even be able to upstream such a solution if we're lucky.
