### ISSUE TITLE
MarkdownHeading shouldn't use scale for text size

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-framework#4525]
https://github.com/ppy/osu-framework/blob/0b4a9c6834041119e25cab1d00e79acfdfceb980/osu.Framework/Graphics/Containers/Markdown/MarkdownHeading.cs#L39

Or else it'll overflow.

![Kapture 2021-06-17 at 18 34 30](https://user-images.githubusercontent.com/35318437/122492490-b0059080-cf9a-11eb-88d8-009a115fd1d7.gif)

osu!-side example:
![osu_2021-06-17_18-37-45](https://user-images.githubusercontent.com/35318437/122492726-25716100-cf9b-11eb-9976-c9c0255d5221.jpg)

**Comment by gagahpangeran** [comment]
Yes, also this `GetFontSizeByLevel` also bothered me when I implemented `OsuMarkdownContainer`.

Instead of returns actual font size, it returns the scale number, then the heading font size is changed by scaling it based on this number.

I think the good direction is change `GetFontSizeByLevel` to actually returns font size. Then change the heading font size properly instead of using scale.

It's a bit breaking changes, so I need more advise before I attempt to do this.
