### ISSUE TITLE
TranslatableString needs recursive evaluation

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#4530]
See: https://github.com/ppy/osu/issues/13530

This comes from the following localisation:
```
'supporter_filter_quote' => [
    '_' => 'Filtering by :filters requires an active :link',
    'link_text' => 'osu!supporter tag',
]
```
Which is a recursive evaluation of `:filters` and `:link` as translatable strings of their own.

**Comment by bdach** [comment]
Note that this case is even worse in that one of the subparts of the main string is a link. So while recursive evaluation of the string will be sufficient in some cases, in general we also will likely need `TextFlowContainer`/game-side `LinkFlowContainer` to contain `string.Format`-like logic (so that it can invert the order of the subparts if necessary).

I've thought about how that could be done and had a loose plan worked out, but I haven't actually tried it.

**Comment by bdach** [comment]
FYI, I have a very early prototype of how text flow could look with localisation support at https://github.com/ppy/osu-framework/compare/master...bdach:text-flow-localisation-mvp?expand=1.

It's:

* *very* lightly tested (especially with the weird edge-casey API kinks of text flow, such as returning added sprite texts or adding them manually),
* a bit unperformant (replaces contents every time one of the parts is changed),
* doesn't support order inversion,
* will not work with CJK languages because of basing on the assumption of "only `\n` is a break",
* and the data flow was a bit ad hoc (I tried to implement my vision for how it should work in the fewest changes possible)

but I'll see if there is wiggle room for doing better. I wouldn't PR that branch as one pull anyhow, it's likely the first two/three steps of however many.

**Comment by smoogipoo** [comment]
Fwiw, "replaces contents every time one of the parts is changed" is also what I'd have done.
