### ISSUE TITLE
Colour handling is not consistent between shaders

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#4537]
As noticed in https://github.com/ppy/osu/issues/13607#issuecomment-865944769, there is an issue with colour consistency across the rounded and non-rounded shaders, likely due to incorrect colour space conversion order. This is causing incorrect/washed out colours in one of the two scenarios.

**Comment by bdach** [comment]
I found this article that I recall reading once before and which seems relevant here: https://erikmcclure.com/blog/everyone-does-srgb-wrong-because/

Bringing this up since the reversal of srgb application order first happened in #2765 (8e2a2b7) wherein the rationale given for it was exactly that gradients looked wrong.

**Comment by bdach** [comment]
Likely this is a regression from db689dca71272a8670231f2871821838325e28a9, which added an incorrect `toSRGB()` call on the result of `texture2D(m_Sampler, v_TexCoord, -0.9)` (i.e. what used to previously be `lowp vec4 texel`)..
