### ISSUE TITLE
HSV colour picker should account for `Scheduler.HasPendingTasks` while not present

### ISSUE THREAD

**Issue by bundeskanzler114** [ppy/osu-framework#4620]
I was trying to implement a basic chroma/color cycling mode to my UI by changing the value of `Hue` in [HSVColourPicker_HueSelector](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/UserInterface/HSVColourPicker_HueSelector.cs) periodically.

As soon as the colour picker is not visible on the UI, the `Hue`'s `BindValueChanged` event stops triggering and the color of the remaining UI elements is not changed anymore.

If there is not already a property to override this behavior, presuming it is intentional, it'd be good in scenarios like this one to have it. 

However, as noted by @peppy earlier today, this is (most likely) just a misuse of `Bindable`, but I was still advised to post this here. That is, I'd be curious to know what the intended way of adding a rainbow cycle to my UI would be.

**Comment by frenzibyte** [comment]
At that point, you haven't mentioned about the HSV colour picker, which is clearly the issue here and nothing related to `Bindable`s which are working perfectly fine in this case.

The colour picker schedules any received value changed event, which will be invoked on the next frame when the drawable is present, unless `IsPresent` is explicitly overridden to account for `Scheduler.HasPendingTasks`, which sounds like what should happen in the colour picker and likely in any other component that schedules value changed events.

**Comment by bundeskanzler114** [comment]
I see. I thought this was an underlying optimization of `Bindable`. Is there any reason for the colour picker to schedule the value changed events at the moment?

**Comment by frenzibyte** [comment]
You shouldn't actually depend on whether it does or doesn't, but @bdach can answer this one I think.

**Comment by bdach** [comment]
The schedule was there to reduce frequency of updates while the hue selector was being dragged.

I guess there is not much harm in allowing the callbacks to run even if the drawable isn't present. It'll run once a frame at most still.
