### ISSUE TITLE
Ogg Tracks no longer loop correctly

### ISSUE THREAD

**Issue by jai-x** [ppy/osu-framework#4670]
Broken on: `2021.805.0` and `2021.807.0`
Last working correctly `2021.804.0`

Creating a `Track` from a `.ogg` file and playing it with `Looping = true` has a noticeable skip when it reaches the loop point.

The `.ogg` file I noticed this issue with (warning somewhat loud):
[test_ogg.zip](https://github.com/ppy/osu-framework/files/6949724/test_ogg.zip)

**Comment by peppy** [comment]
Are you sure it's specific to `.ogg`? There were some ogg changes in bass for that release, but there's also the larger change of using `BassMix` for all audio, which is a more probable cause. In that case, I'd expect even a `.wav` to fail in the same way as an `.ogg` so it'd be appreciated if you can check/confirm this.

**Comment by jai-x** [comment]
From a quick test of the audio files I have: 
- `.ogg` - hitches on loop
- `.wav` - hitches on loop
- `.mp3` - unaffected

**Comment by bdach** [comment]
This is indeed caused by mixer changes, in particular [the mixtime sync](https://github.com/ppy/osu-framework/blob/b592f77bb95b5b931e441a2578a4b242c0684c99/osu.Framework/Audio/Track/TrackBass.cs#L122-L132) used to restart the track to the preview point. As it turns out, [there is a separate `ChannelSetSync` for channels plugged into a mixer](https://www.un4seen.com/doc/#bassmix/BASS_Mixer_ChannelSetSync.html) which should be called here. As the docs state:

> When used on a decoding channel (eg. a mixer source channel), syncs set with BASS_ChannelSetSync are automatically "mixtime", which means that they will be triggered as soon as the sync event is encountered. But if the mixer output is being played, then there is a playback buffer involved, which will delay the hearing of the sync event. This function compensates for that, delaying the triggering of the sync until the event is actually heard. 

Which explains why the loop broke, as the seek back to 0 in the mixtime sync fires early, and at the point where the playback buffer is heard, the track has already played some time forward in the future.

The worse thing is that this sync was mixtime in the first place because otherwise there could be an audible hitch/delay when looping. Using the mixer variant indeed makes it so that there is a bit of a gap in playback between subsequent loops.

A workaround for this may be to only use the sync callback to reset to preview point if it's actually set, i.e. if it's not 0, and defer to the BASS loop flag otherwise.

Also note that:

> When a source is removed from a mixer, any syncs that have been set on it via this function are automatically removed. If the channel is subsequently plugged back into a mixer, the previous syncs will not still be set on it.

So there is no need to do cleanup - but I'm not sure whether jamming the syncs into `TrackBass.startInternal()` will work 100% either (what if the same sync is registered multiple times?)
