### ISSUE TITLE
Deadlock in new audio code 

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#4671]
Looks like bass getting in a bad state, but likely due to something we're doing:

![rider64_2021-08-08_13-55-42](https://user-images.githubusercontent.com/191335/128621320-31bbd1b1-ceb3-4b0a-9f90-e7ed051bda9d.png)

**Comment by bdach** [comment]
At least in the preview track case this deadlock seems to happen when attempting to stop a channel from within a `BASS_SYNC_END` sync callback, namely this one:

https://github.com/ppy/osu-framework/blob/b592f77bb95b5b931e441a2578a4b242c0684c99/osu.Framework/Audio/Track/TrackBass.cs#L115-L121

That callback raises `Track.Completed`, which game-side [`PreviewTrack` subscribes to](https://github.com/ppy/osu/blob/c8a0b6058f4ba5db1fd79707a5c6fd030997cfd7/osu.Game/Audio/PreviewTrack.cs#L35-L36) and [attempts to stop the track again](https://github.com/ppy/osu/blob/c8a0b6058f4ba5db1fd79707a5c6fd030997cfd7/osu.Game/Audio/PreviewTrack.cs#L99), which is a little bit nonsensical it seems. Removing that stop call fixes.

@peppy did you hit this in other scenarios than preview track? Because if not then that may be just this one misuse.

**Comment by bdach** [comment]
Actually, this is also fixed by using the mixer variant of `ChannelSetSync` (see https://github.com/ppy/osu-framework/issues/4670#issuecomment-894798546).
