### ISSUE TITLE
Main-thread dependency injection

### ISSUE THREAD

**Issue by Tom94** [ppy/osu-framework#475]
Currently we can only access injected dependencies inside `load`, which may be called from background threads. However, often we want access to injected dependencies without being forced to deal with concurrency. One such example is the frequently needed access to `OsuColour`.

Our current proposal to fix this is to split `load` into two methods (e.g. `load` and `loadAsync`), one guaranteed to run on the main thread, and the other potentially async. Both receive their arguments via dependency injection.

**Comment by Tom94** [comment]
After further discussion we found that we would not gain much by `loadAsync`, but if we could instead inject dependencies directly into ctors, that would significantly help.

**Comment by smoogipooo** [comment]
I think this is an important conversation to have in the context of having a method that is run after the ctors are initialized, which is useful for the case of virtual methods in base classes. For example consider the following:

```
abstract class BaseClass
{
    public BaseClass()
    {
        VirtualMethod();
    }

    protected abstract void VirtualMethod();
}

class DerivedClass : BaseClass
{
    private readonly object dependency;
    public DerivedClass(object dependency)
    {
        this.dependency = dependency;
    }

    protected override void VirtualMethod()
    {
        Debug.Assert(dependency != null); // Whoops!
    }
}
```

Apart from that having dependencies injected straight into ctors leads to issues such as having to null check dependencies everywhere because you'd essentially have to define them as optional parameters.

Where do you foresee a use case for non-concurrent loads? Changing this to a proposal instead of high prio issue to reduce the noise.

**Comment by peppy** [comment]
This can be easily achieved by using `[Resolved]` + `LoadComplete` or alternatively just using the async load (I don't think the asynchronous issues mentioned above are still relevant).
