### ISSUE TITLE
The default user language should be taken from the system language

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu-framework#5113]

**Comment by peppy** [comment]
I think this is pretty important to get working. Bit of an oversight until now.

**Comment by huoyaoyuan** [comment]
I did some work about this several days ago. Things to mention:

- The framework sets default locale config to empty string. This sets `CurrentCulture` to neutral and overrides any user preference.
- The game doesn't handle variations of culture. The system default culture is usually with country/region code (`en-US`, `zh-CN` etc), but in osu we use non country/region code version (`en`, `zh`). It should use culture parent chain instead of string StartsWith, to handle complex scenarions like `zh-CN` -> `zh-Hans` -> `zh`.

**Comment by peppy** [comment]
If it helps I can provide the fallback logic stable is using for deciding which culture to set. I know it does something similar to what you are proposing here.

**Comment by Susko3** [comment]
Fixed in https://github.com/ppy/osu-framework/pull/5505. But do note that the language is taken from [the date and time format, and not the system UI language](https://github.com/ppy/osu-framework/pull/5505#issuecomment-1307822990).
