### ISSUE TITLE
Cancelled scheduled delegates are not cleaned up if drawable is not present

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-framework#5416]
These could keep piling up on a non-present drawable and eventually hinder performance, see https://github.com/ppy/osu-framework/pull/5409. `AddOnce` is a good alternative but wouldn't cover all cases (e.g. scheduling more than once for one reason or another), so I've at least marked this with mid-priority for now. Simple way to achieve this may be to separate `Scheduler` into two passes (`Cleanup` and `Update`), one being called regardless of presence while the other depends on it.

**Comment by peppy** [comment]
Your proposal doesn't make much sense. Rather than "called regardless of presence" you'd have to "call on `Add` to perform cleanup". Because you can't just bypass presence and run full subtrees of scheduler cleanup.

I'd argue this is a non-issue. It's already got logging warning against it, and in a case you run into this in the first place you should be using `AddOnce`. Curious on @smoogipoo's thoughts though.

**Comment by frenzibyte** [comment]
Actually you could solve this alternatively by adding a callback from `ScheduledDelegate` that's invoked from `Cancel`, for scheduler to subscribe to and remove delegate from queue.

Also logging would only show that the problem exists, and I'm talking about any potential future scenario where `AddOnce` can't be used.

**Comment by peppy** [comment]
You shouldn't be scheduling anything that much without using `AddOnce`. At that point you want to use `Update`

I'd be against adding a delegate callback. It's unnecessary complexity.

**Comment by smoogipoo** [comment]
I'm heavily against callbacks from `.Cancel()` because then deadlocks become a real possibility. I'll call this one working as intended.
