### ISSUE TITLE
DI source generator does not handle member names that conflict with namespaces

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-framework#5563]
Originally reported in [discord chat](https://discord.com/channels/188630481301012481/589331078574112768/1048711155209752606) with the following error:

> 'OsuGameBase' does not contain a definition for 'Framework' and no accessible extension method 'Framework' accepting a first argument of type 'OsuGameBase' could be found (are you missing a using directive or an assembly reference?)

Happens due to the original component declaring a member with the name `osu`, which gets prioritised over the `osu` namespace, thus showing the error seen above. A general fix would be to prefix all class references with `global::` to avoid such conflict (originally proposed [here](https://discord.com/channels/188630481301012481/589331078574112768/1048712345033117876)).

**Comment by bdach** [comment]
I need to sleep, so here's an update for now. This gets worse when considering nested types. The nice and easy case is

```csharp

public partial class ConflictGenerator : osu.Framework.Graphics.Drawable
{
    private bool osu;

    [osu.Framework.Allocation.Cached]
    public object CachedProperty { get; set; }

    [osu.Framework.Allocation.Resolved]
    public object ResolvedProperty { get; set; }

    [osu.Framework.Allocation.BackgroundDependencyLoader]
    private void load(object dependency)
    {
    }
}
```

as in the OP, which can only affect instance method bodies. The horrible, terrible, no-good case is

```csharp
namespace osu;

public partial class NestedConflictGenerator : osu.Framework.Graphics.Drawable
{
    [global::osu.Framework.Allocation.BackgroundDependencyLoader]
    private void load()
    {
    }

    [global::osu.Framework.Allocation.Resolved]
    private object resolvedMember { get; set; }

    public class osu
    {
    }
}
```

wherein the inner `osu` class can type with *any and every* typename spec emitted inside the partial class in the generated files.

String-appending `global::` is incorrect (except for places where the type names are already full strings) because `string::object` is not correct. [`SymbolDisplayFormat.FullyQualifiedFormat`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.symboldisplayformat.fullyqualifiedformat?view=roslyn-dotnet-4.3.0) looks promising as a remedy.

I'm willing to take a stab at this tomorrow but will yield if told to.
