### ISSUE TITLE
Various `wglMakeCurrent()` errors are spammed to log when using Veldrid / OpenGL

### ISSUE THREAD

**Issue by Susko3** [ppy/osu-framework#5688]
I know that Veldrid+OpenGL is not a priority, so I'm reporting for visibility.
Tested on `visual-tests`, and it looks fine, so I'm not sure what the errors are about.

The only three that appear (the second and third mostly seem to appear when the window is obscured or minimized):

```cs
2023-03-19 15:00:05 [verbose]: SDL error log [debug]: wglMakeCurrent(): The requested resource is in use.
2023-03-19 15:00:05 [verbose]: SDL error log [debug]: wglMakeCurrent(): The handle is invalid.
2023-03-19 15:00:05 [verbose]: SDL error log [debug]: wglMakeCurrent(): The requested transformation operation is not supported.
```

Breakpointing the errors leads to:
https://github.com/ppy/osu-framework/blob/e90e308c9b8e34f37890ad40a1da646db5aa6086/osu.Framework/Platform/SDL2/SDL2GraphicsSurface.cs#L176

Full logs: [runtime.log](https://github.com/ppy/osu-framework/files/11011443/runtime.log)

**Comment by Susko3** [comment]
The error is set in https://github.com/libsdl-org/SDL/blob/05b03032f1caf893d2502fe0a5e6313dee7ddab2/src/video/windows/SDL_windowsopengl.c#L829. So I'm marking as windows-specific for now.

**Comment by frenzibyte** [comment]
Quick searching led to https://stackoverflow.com/a/14322797, which seem related here since Veldrid's OpenGL implementation relies on a separate thread for actually executing GL commands. Your best bet would be to comment the existing calls to `MakeCurrent` until the error is gone. The one in `DrawThread.MakeCurrent` might be the most relevant here.
